/**
 * Live client work. Categories drive the grouped sections on /work.
 *
 * Descriptions reflect what each storefront actually sells, taken from the
 * live sites. Screenshots resolve from public/portfolio/shots or the asset
 * base; missing ones fall back to a generated mockup.
 */
export const CATEGORIES = [
  { key: "shopify", label: "Shopify Stores", eyebrow: "SHOPIFY" },
  { key: "chatbot", label: "AI Chatbots & Voice", eyebrow: "AI CHATBOTS" },
  { key: "automation", label: "Automations", eyebrow: "AUTOMATION" },
];

export const PROJECTS = [
  {
    id: "soundskins",
    category: "shopify",
    name: "SoundSkins Global",
    url: "https://soundskinsglobal.com",
    tag: "Automotive",
    desc: "Acoustic insulation for cars, organised by product series with pre cut kits matched to specific vehicles.",
    tags: ["Theme customization", "Custom Liquid", "Speed"],
    accent: "#a855f7",
    accent2: "#6d28d9",
  },
  {
    id: "elite",
    category: "shopify",
    name: "Elite Auto Gear",
    url: "https://eliteautogear.com/",
    tag: "Car Audio",
    desc: "Car audio retailer carrying speakers, amplifiers, subwoofers and the accessories that go with an install.",
    tags: ["Theme customization", "Custom Liquid", "App integration"],
    accent: "#7c3aed",
    accent2: "#a855f7",
  },
  {
    id: "gohaus",
    category: "shopify",
    name: "Haus",
    url: "https://gohaus.com/",
    tag: "Athletic Apparel",
    desc: "Performance and lifestyle clothing for men, spanning tanks, hoodies, shorts and training accessories.",
    tags: ["Custom theme", "Speed", "Collections"],
    accent: "#8b5cf6",
    accent2: "#4f46e5",
  },
  {
    id: "curatedchrome",
    category: "shopify",
    name: "Curated Chrome",
    url: "https://curatedchrome.com/",
    tag: "Jewellery",
    desc: "Statement chrome and sterling silver pieces, from watches and rings through to necklaces and earrings.",
    tags: ["Product pages", "Custom Liquid", "Professional design"],
    accent: "#a78bfa",
    accent2: "#6d28d9",
  },
  {
    id: "chicagofragrance",
    category: "shopify",
    name: "Chicago Fragrance",
    url: "https://chicagofragrance.com/",
    tag: "Fragrance",
    desc: "Designer, niche and rare discontinued scents, backed by two physical stores serving the Chicago area.",
    tags: ["Theme customization", "Search", "App integration"],
    accent: "#9333ea",
    accent2: "#7c3aed",
  },
  {
    id: "kiaura",
    category: "shopify",
    name: "KIAURA Eyewear",
    url: "https://kiauraeyewear.com/",
    tag: "Eyewear",
    desc: "A curated range of vintage and designer frames, built to carry running promotions without a redesign.",
    tags: ["Custom Liquid", "Promotions", "Speed"],
    accent: "#6d28d9",
    accent2: "#a855f7",
  },
  {
    id: "aug11",
    category: "shopify",
    name: "Aug11",
    url: "https://aug11.co/",
    tag: "Headwear",
    desc: "Premium hats sold on a perfect fit guarantee, across new arrivals, best sellers and limited drops.",
    tags: ["Custom theme", "Product drops", "Professional design"],
    accent: "#8b5cf6",
    accent2: "#7c3aed",
  },
  {
    id: "coastal1776",
    category: "shopify",
    name: "Coastal 1776",
    url: "https://coastal1776.com/",
    tag: "Resort Wear",
    desc: "Luxury resort and beachwear, covering linen shirts, dresses, shorts and everyday coastal accessories.",
    tags: ["Theme customization", "Lookbook", "Speed"],
    accent: "#a855f7",
    accent2: "#4f46e5",
  },
  {
    id: "heart4kicks",
    category: "shopify",
    name: "Heart4Kicks",
    url: "https://heart4kicks.com/",
    tag: "Sneaker Accessories",
    desc: "Charms, patches and apparel for customising sneakers, alongside bookable styling sessions.",
    tags: ["Custom Liquid", "Booking flow", "App integration"],
    accent: "#c084fc",
    accent2: "#7c3aed",
  },
  {
    id: "lalascloset",
    category: "shopify",
    name: "Lala's Closet Boutique",
    url: "https://www.lalasclosetboutique.com/",
    tag: "Family Apparel",
    desc: "A family boutique carrying women's, men's and children's clothing plus footwear under one roof.",
    tags: ["Theme customization", "Collections", "Speed"],
    accent: "#a78bfa",
    accent2: "#4f46e5",
  },
  {
    id: "usa250",
    category: "shopify",
    name: "250 USA Celebration",
    url: "https://250usacelebration.com/",
    tag: "Commemorative Apparel",
    desc: "Commemorative clothing for America's 250th anniversary, spanning tees, hoodies, dresses and accessories.",
    tags: ["Custom theme", "Seasonal launch", "Collections"],
    accent: "#9333ea",
    accent2: "#6d28d9",
  },
  {
    id: "gmills",
    category: "shopify",
    name: "GMills Inc",
    url: "https://gmillsinc.myshopify.com/",
    tag: "Memorials",
    desc: "Personalised granite headstones, markers and benches, sold with design consultation and installation.",
    tags: ["Custom forms", "Custom Liquid", "Professional design"],
    accent: "#7c3aed",
    accent2: "#8b5cf6",
  },
  {
    id: "cybex",
    category: "shopify",
    name: "Cybex",
    url: "https://cybex.shopping/",
    tag: "Activewear",
    desc: "Premium activewear for men and women, from tracksuits and hoodies through to leggings and training gear.",
    tags: ["Custom theme", "Speed", "Professional design"],
    accent: "#8b5cf6",
    accent2: "#6d28d9",
  },
  {
    id: "rela",
    category: "shopify",
    name: "RELA",
    url: "https://liverela.com",
    tag: "Pet Care",
    desc: "A pet care brand currently in pre launch, sitting behind a coming soon page until it opens.",
    tags: ["Theme setup", "Pre launch"],
    accent: "#6d28d9",
    accent2: "#8b5cf6",
  },
];

/** Projects for one category, in listed order. */
export const byCategory = (key) => PROJECTS.filter((p) => p.category === key);

/** Only the categories that actually have work in them. */
export const populatedCategories = () =>
  CATEGORIES.filter((c) => PROJECTS.some((p) => p.category === c.key));
